GET http://localhost:3000/carts

###get cart by user
GET http://localhost:3000/carts/getcart/b7c13bdc-ad63-4573-b521-e45ba8470964

###Get my cart
GET http://localhost:3000/carts/mycart


### Add prouct
PATCH http://localhost:3000/carts/91b08d73-2527-4bf8-9a5f-b8e8e9c5c059
Content-Type: application/json

{
  "productId": "a63c3ba3-1345-401a-9e9f-769508b57204"
}

###delete cart
DELETE http://localhost:3000/carts/trash/6c41b200-6cd0-4d3f-8daa-c752a3bf287f

###dele useless carts
DELETE http://localhost:3000/carts/trash