###Create new user
POST  http://localhost:3000/users/auth/signup
Content-Type: application/json

{
  "username": "pedro",
  "email":"pedro@gmail.com",
  "password": "test1234"
}

###login User
POST  http://localhost:3000/users/auth/signin
Content-Type: application/json

{
  "email":"dracula@gmail.com",
  "password": "test1234"
}

### sign out
GET http://localhost:3000/auth/signout

###get current signin user
GET http://localhost:3000/users/auth/whoiam

### Find all Users
GET http://localhost:3000/users


### Find user by id
GET http://localhost:3000/users/99f362b1-2ef3-42fe-815d-2a5fa51e4da7

###Delete user
DELETE http://localhost:3000/users/c1551414-922f-4446-92dd-bc82cfd643bb
### update users info
PATCH http://localhost:3000/users/update/d7eff0d2-c397-4b8d-a3b4-5d4d40b525fc
Content-Type: application/json

{
  "email":"prietro@gmil.com",
  "confirmPassword": "test1234"
}

### update me
PATCH http://localhost:3000/users/updateMe
Content-Type: application/json

{
  "email":"me@gmil.com",
  "confirmPassword": "test1234"
}


###gen users
POST http://localhost:3000/users/seed/10

### carts for  user
PATCH http://localhost:3000/users/gencarts