###Create project
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "matreal",
  "price": 500000,
  "percentageDiscount": 1,
  "stock": 2,
  "description": "good desk for your bedroom",
  "color": "yellow",
  "size": "large",
  "image": "grinder.png",
  "category": "db2f5e58-51b1-4289-9bf1-70de7537edde"

}

###Find all products || product by name
GET http://localhost:3000/products?page=4&pageSize=10

### Find product by id
GET http://localhost:3000/products/MOTR03YE

###Update product
PATCH http://localhost:3000/products/MON01GR
Content-Type: application/json

{
  "name":"levioso"
}

###Delete Product
DELETE http://localhost:3000/products/986db272-8445-4ab9-b9a6-011c92374dca


###gen products
GET http://localhost:3000/products/seed/1