###Create project
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "montreal",
  "price": 500000,
  "percentageDiscount": 1,
  "stock": 2,
  "description": "good desk for your bedroom",
  "color": "yellow",
  "size": "small",
  "image": "grinder.png"
}

###Find all products || product by name
GET http://localhost:3000/products?grinder

### Find product by id
GET http://localhost:3000/products/MON01GR

###Update user
PATCH http://localhost:3000/products/MON01GR
Content-Type: application/json

{
  "name":"levioso"
}

###Delete Product
DELETE http://localhost:3000/products/986db272-8445-4ab9-b9a6-011c92374dca