###create category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "cama",
  "productsId": ["MOTR03YE", "ELEG02#9", "HAND01#C"]

}

###get all categories
GET http://localhost:3000/categories

###get a category
GET http://localhost:3000/categories/81aaebc5-f102-4f40-af41-223f554222c6

###delete categoria
DELETE http://localhost:3000/categories/21263a50-35e8-42b3-9b05-4630481b2c34

### seed
GET http://localhost:3000/categories/seed/10