GET http://localhost:3000/carts

###get cart by user
GET http://localhost:3000/carts/b7c13bdc-ad63-4573-b521-e45ba8470964
### Add prouct
PATCH http://localhost:3000/carts/b7c13bdc-ad63-4573-b521-e45ba8470964
Content-Type: application/json

{
  "productId": "23d6ff59-bcce-4f4c-bdda-be0522dc601c",
  "quantity": 5
}

###delete cart
DELETE http://localhost:3000/carts/ad606e55-c611-42c7-80be-46b4b59421b7

###dele useless carts
DELETE http://localhost:3000/carts/trash